export const hiragana = {
  a: {
    roman: '00041.svg',
    japan: '03042.svg',
    noun: {
      1: {
        ame: {
          svg: 'ame.svg',
          jp: 'あめ',
          pt: 'chuva',
          en: 'rain',
          jpP: 'あめがふっている',
          yomi: 'ame ga futteiru',
          ptP: 'Está chovendo',
          enP: "It's raining",
        },
      },
      2: {
        ashi: {
          svg: 'ashi.svg',
          jp: 'あし',
          pt: 'pé',
          en: 'foot',
          jpP: 'あしがいたい',
          yomi: 'ashi ga itai',
          ptP: 'Meu pé dói',
          enP: 'My foot hurts',
        },
      },
      3: {
        ase: {
          svg: 'ase.svg',
          jp: 'あせ',
          pt: 'suor',
          en: 'sweat',
          jpP: 'あせをかく',
          yomi: 'ase wo kaku',
          ptP: 'Soar',
          enP: 'To sweat',
        },
      },
    },
    verb: {
      1: {
        aruku: {
          svg: 'aruku.svg',
          jp: 'あるく',
          pt: 'andar',
          en: 'to walk',
          jpP: 'がっこうまであるいていく',
          yomi: 'gakkou made aruiteiku',
          ptP: 'Andar até a escola',
          enP: 'Walk to school',
        },
      },
      2: {
        asobu: {
          svg: 'asobu.svg',
          jp: 'あそぶ',
          pt: 'brincar',
          en: 'to play',
          jpP: 'いっしょにあそぼう',
          yomi: 'isshou ni asobou',
          ptP: 'Vamos brincar juntos',
          enP: "Let's play together",
        },
      },
      3: {
        arau: {
          svg: 'arau.svg',
          jp: 'あらう',
          pt: 'lavar',
          en: 'to wash',
          jpP: 'てをあらった',
          yomi: 'te wo aratta',
          ptP: 'Lavei as mãos',
          enP: 'I washed my hands',
        },
      },
    },
  },
  i: {
    roman: '00049.svg',
    japan: '03044.svg',
    noun: {
      1: {
        isu: {
          svg: 'isu.svg',
          jp: 'いす',
          pt: 'cadeira',
          en: 'chair',
          jpP: 'いすにすわった',
          yomi: 'isu ni suwatta',
          ptP: 'Sentou na cadeira',
          enP: 'Sat on the chair',
        },
      },
      2: {
        ie: {
          svg: 'ie.svg',
          jp: 'いえ',
          pt: 'casa',
          en: 'home',
          jpP: 'いえにかえる',
          yomi: 'ie ni kaeru',
          ptP: 'Vou para casa',
          enP: 'I am going home',
        },
      },
      3: {
        inu: {
          svg: 'inu.svg',
          jp: 'いぬ',
          pt: 'cachorro',
          en: 'dog',
          jpP: 'いぬをさんぽする',
          yomi: 'inu wo sanposuru',
          ptP: 'Levar o cachorro para passear',
          enP: 'To walk the dog',
        },
      },
    },
    verb: {
      1: {
        iku: {
          svg: 'iku.svg',
          jp: 'iku',
          pt: 'ir',
          en: 'to go',
          jpP: 'こうえんにいこう',
          yomi: 'kouen ni ikou',
          ptP: 'Vamos ao parque!',
          enP: "Let's go to the park!",
        },
      },
      2: {
        iu: {
          svg: 'iu.svg',
          jp: 'iu',
          pt: 'falar',
          en: 'to say',
          jpP: 'おおごえでいう',
          yomi: 'oogoe de iu',
          ptP: 'Falar alto',
          enP: 'To say out loud',
        },
      },
      3: {
        ijimeru: {
          svg: 'ijimeru.svg',
          jp: 'いじめる',
          pt: 'mau tratar',
          en: 'to bully',
          jpP: '人をいじめる',
          yomi: 'hito wo ijimeru',
          ptP: 'Maltratar alguém',
          enP: 'To bully someone',
        },
      },
    },
  },
  u: {},
  e: {},
  o: {},
}
